package com.opspilot.tenant.dto;

import com.opspilot.tenant.domain.entity.Role;
import java.util.UUID;

/**
 * Internal request sent by tenant-service to auth-service to provision a new credential account.
 *
 * <p>The {@code userId} is generated by tenant-service and must be used as the primary key
 * in auth-service so that both services share the same user UUID. The password is transmitted
 * in plaintext to auth-service over the internal network and hashed there before storage.
 */
public record InternalCreateAuthUserRequest(
        UUID userId,
        UUID tenantId,
        String email,
        String password,
        Role role
) {
}
