package com.opspilot.apigateway.util.logging;

import java.util.concurrent.atomic.AtomicReference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

/**
 * Spring Cloud Gateway global filter that logs every proxied request at the
 * gateway level, including method, path, HTTP status, and wall-clock duration.
 *
 * <p>This filter runs at {@link Ordered#HIGHEST_PRECEDENCE} so it wraps the entire
 * downstream filter chain, giving an accurate end-to-end timing measurement.
 * The correlation ID ({@code X-Request-Id}) is read from the already-mutated
 * request (normalised/generated by {@link CorrelationIdWebFilter} which runs
 * earlier in the web-filter chain) and included in every log line so requests
 * can be traced across service boundaries in a log aggregator.
 */
@Component
public class GatewayRequestLoggingFilter implements GlobalFilter, Ordered {

    private static final Logger log = LoggerFactory.getLogger(GatewayRequestLoggingFilter.class);

    /**
     * Intercepts the proxied request, records the start time, delegates to the
     * remaining filter chain, then emits a structured log line when the reactive
     * stream terminates (either normally or with an error).
     *
     * <p>An {@link AtomicReference} is used to capture any error thrown inside the
     * reactive pipeline so it is accessible inside the {@code doFinally} callback,
     * which executes on whichever thread the reactive scheduler assigns — potentially
     * different from the thread that called {@code filter}.
     *
     * @param exchange the current server web exchange containing request and response
     * @param chain    the remaining gateway filter chain to delegate to
     * @return a {@link Mono} that completes when the proxied response has been fully written
     */
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest requestWithCorrelation = exchange.getRequest();
        // The correlation ID was already normalised/generated by CorrelationIdWebFilter;
        // read it here so it can be included in every log line for this request
        String requestId = RequestCorrelation.normalizeOrGenerate(
                requestWithCorrelation.getHeaders().getFirst(RequestCorrelation.HEADER_NAME)
        );

        long startedAtNanos = System.nanoTime();
        // AtomicReference is required because the doOnError and doFinally callbacks
        // may execute on different threads in the reactive scheduler
        AtomicReference<Throwable> errorRef = new AtomicReference<>();

        return chain.filter(exchange)
                .doOnError(errorRef::set)
                .doFinally(signalType -> {
                    // Convert nanosecond precision to milliseconds for human-readable log output
                    long durationMs = (System.nanoTime() - startedAtNanos) / 1_000_000;
                    // Fall back to 500 if the response code was never written (e.g. connection reset)
                    int status = exchange.getResponse().getStatusCode() == null
                            ? HttpStatus.INTERNAL_SERVER_ERROR.value()
                            : exchange.getResponse().getStatusCode().value();

                    Throwable error = errorRef.get();
                    if (error == null) {
                        log.info(
                                "gateway_request_completed method={} path={} status={} durationMs={} requestId={}",
                                requestWithCorrelation.getMethod(),
                                requestWithCorrelation.getPath().value(),
                                status,
                                durationMs,
                                requestId
                        );
                    } else {
                        log.error(
                                "gateway_request_failed method={} path={} status={} durationMs={} requestId={} message={}",
                                requestWithCorrelation.getMethod(),
                                requestWithCorrelation.getPath().value(),
                                status,
                                durationMs,
                                requestId,
                                error.getMessage(),
                                error
                        );
                    }
                });
    }

    /**
     * Returns the filter's order in the global filter chain.
     *
     * <p>Running at {@link Ordered#HIGHEST_PRECEDENCE} ensures this filter wraps
     * the entire downstream chain so the timing measurement covers all processing,
     * including routing, load-balancing, and downstream response streaming.
     *
     * @return {@link Ordered#HIGHEST_PRECEDENCE}
     */
    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE;
    }
}
